// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_comm.DB.EF;

namespace e_comm.Migrations
{
    [DbContext(typeof(DBcon))]
    partial class DBconModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("e_comm.DB.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Ade Kaye",
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 482, DateTimeKind.Utc).AddTicks(9196),
                            GenderId = 2,
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 482, DateTimeKind.Utc).AddTicks(9196)
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Bedat",
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(577),
                            GenderId = 2,
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(577)
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Bertha",
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(618),
                            GenderId = 2,
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(618)
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Eterna",
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(620),
                            GenderId = 2,
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(620)
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Casio",
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(621),
                            GenderId = 1,
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(621)
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Rolex",
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(622),
                            GenderId = 1,
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(622)
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Omega",
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(623),
                            GenderId = 1,
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(623)
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Certina",
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(624),
                            GenderId = 1,
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 483, DateTimeKind.Utc).AddTicks(624)
                        });
                });

            modelBuilder.Entity("e_comm.DB.Domain.ChangePasswordCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChangePasswords");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 485, DateTimeKind.Utc).AddTicks(5748),
                            GenderName = "Male",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 485, DateTimeKind.Utc).AddTicks(5748)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 485, DateTimeKind.Utc).AddTicks(6060),
                            GenderName = "Female",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 485, DateTimeKind.Utc).AddTicks(6060)
                        });
                });

            modelBuilder.Entity("e_comm.DB.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("ImageRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GenderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 488, DateTimeKind.Utc).AddTicks(9500),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina-m/certina1.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 488, DateTimeKind.Utc).AddTicks(9500),
                            Price = 299.99000000000001,
                            ProductName = "Certina",
                            ShortDescription = " DS Podium Automatic Grey Dial Men's Watch"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1012),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina-m/certina2.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1012),
                            Price = 220.99000000000001,
                            ProductName = "Certina",
                            ShortDescription = "DS First Ceramic Black Leather Men's Watch"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1064),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina-m/certina3.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1064),
                            Price = 529.99000000000001,
                            ProductName = "Certina",
                            ShortDescription = "DS-1 Big Date Automatic Men's Watch"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1065),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina-m/certina4.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1065),
                            Price = 189.99000000000001,
                            ProductName = "Certina",
                            ShortDescription = "DS Blue Ribbon Quartz Black Dial Men's Watch"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1067),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega-m/omega1.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1067),
                            Price = 3949.9899999999998,
                            ProductName = "Omega",
                            ShortDescription = "Seamaster Automatic Blue Dial Men's Watch"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1068),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega-m/omega2.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1068),
                            Price = 3919.9899999999998,
                            ProductName = "Omega",
                            ShortDescription = "Seamaster Automatic Grey Dial Men's Watch"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1069),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega-m/omega3.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1069),
                            Price = 4099.9899999999998,
                            ProductName = "Omega",
                            ShortDescription = "Seamaster Automatic Grey Dial Men's Watch"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1071),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega-m/omega4.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1071),
                            Price = 5594.9899999999998,
                            ProductName = "Omega",
                            ShortDescription = "Seamaster Automatic Chronometer Men's"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1072),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex-m/rolex1.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1072),
                            Price = 8849.9899999999998,
                            ProductName = "Rolex",
                            ShortDescription = "Air King Black Dial Stainless Steel Men's"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1073),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex-m/rolex2.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1073),
                            Price = 14324.99,
                            ProductName = "Rolex",
                            ShortDescription = "Oyster Perpetual Submariner Black Dial Black Cerachrom Bezel Steel Men's Watch"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1074),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex-m/rolex3.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1074),
                            Price = 20149.990000000002,
                            ProductName = "Rolex",
                            ShortDescription = "Submariner Kermit Automatic Chronometer Black Dial Men's Watch"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1076),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex-m/rolex4.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1076),
                            Price = 7194.9899999999998,
                            ProductName = "Rolex",
                            ShortDescription = "Pre-owned Datejust 36 Automatic Diamond Blue Dial Men's Watch"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1077),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio-m/casio1.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1077),
                            Price = 178.99000000000001,
                            ProductName = "Casio",
                            ShortDescription = "G-Shock Men's Analog-Digital Watch"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1078),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio-m/casio2.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1078),
                            Price = 124.98999999999999,
                            ProductName = "Casio",
                            ShortDescription = "G Shock Analog-Digital Dial Black and Gold Resin Men's Watch GA110GB-1ACR"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1079),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio-m/casio3.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1079),
                            Price = 74.989999999999995,
                            ProductName = "Casio",
                            ShortDescription = "G Shock Grey Digital Dial Resin Men's Watch"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1081),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio-m/casio4.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1081),
                            Price = 59.990000000000002,
                            ProductName = "Casio",
                            ShortDescription = "G-Shock Military Men's Watch"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1082),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adee kaye-f/ak-1.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1082),
                            Price = 85.989999999999995,
                            ProductName = "Adee Kaye",
                            ShortDescription = "Exotic Snowflake Dial Ladies Watc"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1083),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adee kaye-f/ak-2.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1083),
                            Price = 111.98999999999999,
                            ProductName = "Adee Kaye",
                            ShortDescription = "Yahtch II Blue Dia Ladies Chronograph Watch"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1084),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adee kaye-f/ak-3.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1084),
                            Price = 85.989999999999995,
                            ProductName = "Adee Kaye",
                            ShortDescription = "Beverly Hills Exotic Ladies Leather Watch"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1085),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adee kaye-f/ak-4.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1085),
                            Price = 85.989999999999995,
                            ProductName = "Adee Kaye",
                            ShortDescription = "Brown Dial Ladies Crystal Watch"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1087),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bedat-f/bedat1.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1087),
                            Price = 5674.9899999999998,
                            ProductName = "Bedat",
                            ShortDescription = "No. 3 Diamond Steel Ladies Watch"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1088),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bedat-f/bedat2.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1088),
                            Price = 4619.9899999999998,
                            ProductName = "Bedat",
                            ShortDescription = "No 2 Mother of Pearl Diamond Stainless Steel Ladies Watch"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1089),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bedat-f/bedat3.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1089),
                            Price = 1119.99,
                            ProductName = "Bedat",
                            ShortDescription = "No 3 Silver Dial Stainless Steel Ladies Watch"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1090),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha-f/bertha1.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1090),
                            Price = 139.99000000000001,
                            ProductName = "Bertha",
                            ShortDescription = "Dolly Quartz Silver Dial Ladies Watch"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1091),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha-f/bertha2.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1091),
                            Price = 119.98999999999999,
                            ProductName = "Bertha",
                            ShortDescription = "Cecelia Crystal Green Dial Green Leather Ladies Watch"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1093),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha-f/bertha3.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1093),
                            Price = 249.99000000000001,
                            ProductName = "Bertha",
                            ShortDescription = "Cecelia Crystal Green Dial Green Leather Ladies Watch"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1135),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha-f/bertha4.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1135),
                            Price = 179.99000000000001,
                            ProductName = "Bertha",
                            ShortDescription = "Dixie Quartz Crystal Silver Dial Ladies Watch"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1137),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna-f/eterna1.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1137),
                            Price = 174.99000000000001,
                            ProductName = "Eterna",
                            ShortDescription = "Eternity Quartz Diamond White Dial Ladies"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1138),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna-f/eterna2.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1138),
                            Price = 209.99000000000001,
                            ProductName = "Eterna",
                            ShortDescription = "Eternity Quartz Diamond White Dial Ladies Watch"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1140),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna-f/eterna3.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1140),
                            Price = 1349.99,
                            ProductName = "Eterna",
                            ShortDescription = "Grace Open Art Automatic Mother of Pearl Diamond Ladies Watch"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1141),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna-f/eterna4.jpg",
                            ModifedAt = new DateTime(2021, 4, 1, 15, 27, 50, 489, DateTimeKind.Utc).AddTicks(1141),
                            Price = 174.99000000000001,
                            ProductName = "Eterna",
                            ShortDescription = "Eternity Quartz Diamond White Dial Ladies Watch"
                        });
                });

            modelBuilder.Entity("e_comm.DB.Domain.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("e_comm.DB.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChangePasswordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TokenId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangePasswordId")
                        .IsUnique()
                        .HasFilter("[ChangePasswordId] IS NOT NULL");

                    b.HasIndex("GenderId");

                    b.HasIndex("TokenId")
                        .IsUnique()
                        .HasFilter("[TokenId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Category", b =>
                {
                    b.HasOne("e_comm.DB.Domain.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Payment", b =>
                {
                    b.HasOne("e_comm.DB.Domain.Product", "Product")
                        .WithMany("Payments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comm.DB.Domain.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Product", b =>
                {
                    b.HasOne("e_comm.DB.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comm.DB.Domain.Gender", "Gender")
                        .WithMany("Products")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("e_comm.DB.Domain.User", b =>
                {
                    b.HasOne("e_comm.DB.Domain.ChangePasswordCode", "ChangePassword")
                        .WithOne("User")
                        .HasForeignKey("e_comm.DB.Domain.User", "ChangePasswordId");

                    b.HasOne("e_comm.DB.Domain.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comm.DB.Domain.Token", "Token")
                        .WithOne("User")
                        .HasForeignKey("e_comm.DB.Domain.User", "TokenId");

                    b.Navigation("ChangePassword");

                    b.Navigation("Gender");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("e_comm.DB.Domain.ChangePasswordCode", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Gender", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Product", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Token", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("e_comm.DB.Domain.User", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
