// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_comm.DB.EF;

namespace e_comm.Migrations
{
    [DbContext(typeof(DBcon))]
    partial class DBconModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("e_comm.DB.Domain.BillingDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BillingDetails");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("ImageRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Ade Kaye",
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(4042),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adekayee.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(4042)
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Bedat",
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5699),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bedat.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5699)
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Bertha",
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5752),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5752)
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Eterna",
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5753),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5753)
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Casio",
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5754),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5754)
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Rolex",
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5756),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5756)
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Omega",
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5757),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5757)
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Certina",
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5758),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 468, DateTimeKind.Utc).AddTicks(5758)
                        });
                });

            modelBuilder.Entity("e_comm.DB.Domain.ChangePasswordCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ChangePasswords");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 471, DateTimeKind.Utc).AddTicks(196),
                            GenderName = "Male",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 471, DateTimeKind.Utc).AddTicks(196)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 471, DateTimeKind.Utc).AddTicks(498),
                            GenderName = "Female",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 471, DateTimeKind.Utc).AddTicks(498)
                        });
                });

            modelBuilder.Entity("e_comm.DB.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("ImageRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GenderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(4250),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina-m/certina1.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(4250),
                            Price = 299.99000000000001,
                            ProductName = "Certina",
                            ShortDescription = " DS Podium Automatic Grey Dial Men's Watch"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5603),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina-m/certina2.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5603),
                            Price = 220.99000000000001,
                            ProductName = "Certina",
                            ShortDescription = "DS First Ceramic Black Leather Men's Watch"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5697),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina-m/certina3.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5697),
                            Price = 529.99000000000001,
                            ProductName = "Certina",
                            ShortDescription = "DS-1 Big Date Automatic Men's Watch"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5699),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/certina-m/certina4.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5699),
                            Price = 189.99000000000001,
                            ProductName = "Certina",
                            ShortDescription = "DS Blue Ribbon Quartz Black"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5700),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega-m/omega1.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5700),
                            Price = 3949.9899999999998,
                            ProductName = "Omega",
                            ShortDescription = "Seamaster Automatic Blue Dial Men's Watch"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5703),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega-m/omega2.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5703),
                            Price = 3919.9899999999998,
                            ProductName = "Omega",
                            ShortDescription = "Seamaster Automatic Grey Dial Men's Watch"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5704),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega-m/omega3.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5704),
                            Price = 4099.9899999999998,
                            ProductName = "Omega",
                            ShortDescription = "Seamaster Automatic Grey Dial Men's Watch"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5705),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/omega-m/omega4.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5705),
                            Price = 5594.9899999999998,
                            ProductName = "Omega",
                            ShortDescription = "Seamaster Automatic Chronometer Men's"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5707),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex-m/rolex1.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5707),
                            Price = 8849.9899999999998,
                            ProductName = "Rolex",
                            ShortDescription = "Air King Black Dial Stainless Steel Men's"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5708),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex-m/rolex2.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5708),
                            Price = 14324.99,
                            ProductName = "Rolex",
                            ShortDescription = "Oyster Perpetual Submariner Black Dial "
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5709),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex-m/rolex3.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5709),
                            Price = 20149.990000000002,
                            ProductName = "Rolex",
                            ShortDescription = "Submariner Kermit Automatic Chronometer "
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5710),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/rolex-m/rolex4.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5710),
                            Price = 7194.9899999999998,
                            ProductName = "Rolex",
                            ShortDescription = "Pre-owned Datejust 36 Automatic Diamond"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5712),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio-m/casio1.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5712),
                            Price = 178.99000000000001,
                            ProductName = "Casio",
                            ShortDescription = "G-Shock Men's Analog-Digital Watch"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5713),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio-m/casio2.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5713),
                            Price = 124.98999999999999,
                            ProductName = "Casio",
                            ShortDescription = "G Shock Analog-Digital Dial Black "
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5714),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio-m/casio3.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5714),
                            Price = 74.989999999999995,
                            ProductName = "Casio",
                            ShortDescription = "G Shock Grey Digital Dial Resin "
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5715),
                            GenderId = 1,
                            ImageRoute = "../images/HomePage/casio-m/casio4.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5715),
                            Price = 59.990000000000002,
                            ProductName = "Casio",
                            ShortDescription = "G-Shock Military Men's Watch"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5716),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adee kaye-f/ak-1.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5716),
                            Price = 85.989999999999995,
                            ProductName = "Adee Kaye",
                            ShortDescription = "Exotic Snowflake Dial Ladies Watc"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5717),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adee kaye-f/ak-2.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5717),
                            Price = 111.98999999999999,
                            ProductName = "Adee Kaye",
                            ShortDescription = "Yahtch II Blue Dia Ladies Chronograph Watch"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5719),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adee kaye-f/ak-3.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5719),
                            Price = 85.989999999999995,
                            ProductName = "Adee Kaye",
                            ShortDescription = "Beverly Hills Exotic Ladies Leather Watch"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5720),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/adee kaye-f/ak-4.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5720),
                            Price = 85.989999999999995,
                            ProductName = "Adee Kaye",
                            ShortDescription = "Brown Dial Ladies Crystal Watch"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5721),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bedat-f/bedat1.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5721),
                            Price = 5674.9899999999998,
                            ProductName = "Bedat",
                            ShortDescription = "No. 3 Diamond Steel Ladies Watch"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5722),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bedat-f/bedat2.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5722),
                            Price = 4619.9899999999998,
                            ProductName = "Bedat",
                            ShortDescription = "No 2 Mother of Pearl Diamond Stainless "
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5723),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bedat-f/bedat3.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5723),
                            Price = 1119.99,
                            ProductName = "Bedat",
                            ShortDescription = "No 3 Silver Dial Stainless Steel "
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5725),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha-f/bertha1.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5725),
                            Price = 139.99000000000001,
                            ProductName = "Bertha",
                            ShortDescription = "Dolly Quartz Silver Dial Ladies Watch"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5726),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha-f/bertha2.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5726),
                            Price = 119.98999999999999,
                            ProductName = "Bertha",
                            ShortDescription = "Cecelia Crystal Green Dial Green "
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5727),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha-f/bertha3.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5727),
                            Price = 249.99000000000001,
                            ProductName = "Bertha",
                            ShortDescription = "Cecelia Crystal Green Dial Green "
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5728),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/bertha-f/bertha4.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5728),
                            Price = 179.99000000000001,
                            ProductName = "Bertha",
                            ShortDescription = "Dixie Quartz Crystal Silver "
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5729),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna-f/eterna1.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5729),
                            Price = 174.99000000000001,
                            ProductName = "Eterna",
                            ShortDescription = "Eternity Quartz Diamond White Dial Ladies"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5731),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna-f/eterna2.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5731),
                            Price = 209.99000000000001,
                            ProductName = "Eterna",
                            ShortDescription = "Eternity Quartz Diamond White Dial Ladies Watch"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5732),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna-f/eterna3.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5732),
                            Price = 1349.99,
                            ProductName = "Eterna",
                            ShortDescription = "Grace Open Art Automatic Mother "
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5733),
                            GenderId = 2,
                            ImageRoute = "../images/HomePage/eterna-f/eterna4.jpg",
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 474, DateTimeKind.Utc).AddTicks(5733),
                            Price = 174.99000000000001,
                            ProductName = "Eterna",
                            ShortDescription = "Eternity Quartz Diamond White Dial "
                        });
                });

            modelBuilder.Entity("e_comm.DB.Domain.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("e_comm.DB.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 4, 6, 21, 39, 2, 478, DateTimeKind.Utc).AddTicks(3395),
                            Email = "adiskubat@outlook.com",
                            GenderId = 1,
                            ModifedAt = new DateTime(2021, 4, 6, 21, 39, 2, 478, DateTimeKind.Utc).AddTicks(3395),
                            PasswordHash = "C29v6PDxBQq/0r05p0yzXWxUdm7dH5xQ+Y2sagbcKbY=",
                            PasswordSalt = "NBRH/6nbEfnhdyx9a7w6lA==",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("e_comm.DB.Domain.BillingDetails", b =>
                {
                    b.HasOne("e_comm.DB.Domain.User", "User")
                        .WithOne("BillingDetails")
                        .HasForeignKey("e_comm.DB.Domain.BillingDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Category", b =>
                {
                    b.HasOne("e_comm.DB.Domain.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("e_comm.DB.Domain.ChangePasswordCode", b =>
                {
                    b.HasOne("e_comm.DB.Domain.User", "User")
                        .WithOne("ChangePassword")
                        .HasForeignKey("e_comm.DB.Domain.ChangePasswordCode", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Payment", b =>
                {
                    b.HasOne("e_comm.DB.Domain.Product", "Product")
                        .WithMany("Payments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comm.DB.Domain.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Product", b =>
                {
                    b.HasOne("e_comm.DB.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comm.DB.Domain.Gender", "Gender")
                        .WithMany("Products")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Token", b =>
                {
                    b.HasOne("e_comm.DB.Domain.User", "User")
                        .WithOne("Token")
                        .HasForeignKey("e_comm.DB.Domain.Token", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("e_comm.DB.Domain.User", b =>
                {
                    b.HasOne("e_comm.DB.Domain.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Gender", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("e_comm.DB.Domain.Product", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("e_comm.DB.Domain.User", b =>
                {
                    b.Navigation("BillingDetails");

                    b.Navigation("ChangePassword");

                    b.Navigation("Payments");

                    b.Navigation("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
